import {
    // create naive ui
    create,
    // component
    NConfigProvider,
    NMessageProvider,
    NButton,
    NIcon,
    NInput,
    NDatePicker,
    NMenu,
    NSwitch,
    NLayoutSider,
    NLayout,
    NLayoutHeader,
    NLayoutContent,
    NAvatar,
    NSpace,
    NGrid,
    NGridItem,
    NDivider,
    NGradientText,
    NImage,
    NH1,
    NH2,
    NH3,
    NH4,
    NText,
    NDropdown,
    NCard,
    NTag,
    NPagination,
    NPopconfirm,
    NTooltip,
    NFloatButton,
    NFlex,
    NColorPicker

} from 'naive-ui'
const naive = create({
    components: [
        NConfigProvider,
        NMessageProvider,
        NButton,
        NIcon,
        NInput,
        NDatePicker,
        NMenu,
        NSwitch,
        NLayoutSider,
        NLayout,
        NLayoutHeader,
        NLayoutContent, 
        NAvatar,
        NSpace,
        NGrid,
        NGridItem,
        NDivider,
        NGradientText,
        NImage,
        NH1,
        NH2,
        NH3,
        NH4,
        NText,
        NDropdown,
        NCard,
        NTag,
        NPagination,
        NPopconfirm,
        NTooltip,
        NFloatButton,
        NFlex,
        NColorPicker
    
    ],
})

export default naive
